version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss-flexbugs-fixes
    versions:
    - 5.0.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
    - 4.21.0
  - dependency-name: "@next/bundle-analyzer"
    versions:
    - 10.0.7
    - 10.1.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: playwright-core
    versions:
    - 1.10.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: cypress
    versions:
    - 6.8.0
  - dependency-name: "@nrwl/jest"
    versions:
    - 11.5.2
    - 11.6.0
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
    - 10.1.1
  - dependency-name: "@nrwl/express"
    versions:
    - 11.5.2
    - 11.6.0
  - dependency-name: "@nrwl/react"
    versions:
    - 11.2.7
    - 11.5.2
    - 11.6.0
  - dependency-name: "@nrwl/workspace"
    versions:
    - 11.2.7
    - 11.5.1
    - 11.5.2
    - 11.6.0
  - dependency-name: "@nrwl/next"
    versions:
    - 11.2.7
    - 11.4.0
    - 11.5.2
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.16
  - dependency-name: "@nrwl/web"
    versions:
    - 11.5.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.32
    - 14.14.33
  - dependency-name: "@headlessui/react"
    versions:
    - 0.3.1
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.13.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@nrwl/cypress"
    versions:
    - 11.2.7
    - 11.4.0
  - dependency-name: "@nrwl/tao"
    versions:
    - 11.4.0
  - dependency-name: "@nrwl/cli"
    versions:
    - 11.2.7
