dist: bionic

language: node_js

node_js: lts/*

cache:
  yarn: true

install: yarn

script:
  - yarn nx test helper
  - yarn nx test fetch

jobs:
  include:
    - name: apps/web
      script:
        - yarn nx test web
        - yarn nx e2e web-e2e
      before_deploy:
        - yarn nx:highmem build web --skip-nx-cache
      deploy:
        provider: netlify
        site: $NETLIFY_WEB_ID
        auth: $NETLIFY_AUTH_TOKEN
        dir: apps/web/public
        message: Automatic deployment from Travis CI
        prod: true
        edge: true
        on:
          repo: rayriffy/rayriffy-h
          branch: master
    - name: apps/api
      script:
        - yarn nx test api
      before_deploy:
        - yarn global add vercel
        - yarn nx build api --skip-nx-cache
      deploy:
        provider: script
        script: vercel -t $VERCEL_AUTH_TOKEN --prod
        on:
          repo: rayriffy/rayriffy-h
          branch: master
    - name: apps/poster
      script:
        - yarn nx test poster
        - yarn nx e2e poster-e2e
      before_deploy:
        - yarn nx export poster --skip-nx-cache
        - yarn global add netlify-cli
      deploy:
        provider: netlify
        site: $NETLIFY_POSTER_ID
        auth: $NETLIFY_AUTH_TOKEN
        dir: apps/web/public
        message: Automatic deployment from Travis CI
        prod: true
        edge: true
        on:
          repo: rayriffy/rayriffy-h
          branch: master
