os: osx

language: node_js

node_js: lts/*

cache:
  yarn: true

install: yarn

script:
  - yarn nx test helper
  - yarn nx test fetch

jobs:
  include:
    - name: apps/web
      script:
        - yarn nx test web
        - yarn nx e2e web-e2e
        - yarn nx:highmem build web
      before_deploy:
        - yarn global add netlify-cli
      deploy:
        provider: script
        script: netlify deploy --dir=apps/web/public --message "Automatic deployment from Travis CI" --prod --site $NETLIFY_WEB_ID
        on:
          branch: master
    - name: apps/api
      script:
        - yarn nx test api
        - yarn nx build api
      before_deploy:
        - yarn global add vercel
      deploy:
        provider: script
        script: vercel -t $VERCEL_AUTH_TOKEN --prod
        on:
          branch: master
    - name: apps/poster
      script:
        - yarn nx test poster
        - yarn nx e2e poster-e2e
        - yarn nx export poster
      before_deploy:
        - yarn global add netlify-cli
      deploy:
        provider: script
        script: netlify deploy --dir=dist/apps/poster/exported --message "Automatic deployment from Travis CI" --prod --site $NETLIFY_POSTER_ID
        on:
          branch: master
