name: Test Units

on: [pull_request]

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Init: Summon NodeJS'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: "Cache: node_modules"
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ env.cache-name }}-
            ${{ runner.OS }}-node-
      - name: 'Init: Install dependencies'
        run: |
          yarn install
      - name: 'Nx: Jest'
        run: |
          yarn nx affected:test --base=origin/master
      - name: 'Nx: End-to-End'
        run: |
          yarn nx affected:e2e --base=origin/master
      - name: 'Nx: Lint'
        run: |
          yarn nx affected:lint --base=origin/master
